nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
